### ISSUE TITLE
won't load document

### ISSUE THREAD

**Issue by r2binx** [ONLYOFFICE/onlyoffice-owncloud#121]
everything is supposedly working, the document server is available from the client and the host of course. However, I can't seem to open an existing file nor a new one.
It's just stuck at the loading screen. RAM shouldn't be an issiue with 6GB.

Which logs could I take a look at or have you got any idea what the problem is here?

Thanks! :)

**Comment by onny** [comment]
You should have a look at your browser logs, e.g. javascript console and also the network log to see if all ressources could be loaded.

**Comment by alexanderonlyoffice** [comment]
Hello @r2binx,

Please open browser's console (Console tab in browser's console) when trying to open the file, make a screenshot and send it to us.

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.

**Comment by tomaszbrudzinski** [comment]
I've got the same issue. Console doesn't contain any bugs, but I've found this in /var/log/onlyoffice/documentserver/docservice/out.log:

`error: column "callback" of relation "task_result" does not exist
    at Connection.parseE (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
[2018-10-23 18:29:57.457] [ERROR] nodeJS - error receiving response: docId = undefined type = auth
error: column "callback" of relation "task_result" does not exist
    at Connection.parseE (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)`

Does this mean that the database has not been migrated properly during the update? Should I do something manually?

Please advise

**Comment by alexanderonlyoffice** [comment]
@tomaszbrudzinski, yes, unfortunately, there was some failure with DB while updating. You need to delete the Document Server and the DB. The new DB should be created. Please follow this [link](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx) to find an instruction on how to install Document Server.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
