### ISSUE TITLE
Problems on configuring app

### ISSUE THREAD

**Issue by knife-grinder** [ONLYOFFICE/onlyoffice-owncloud#205]
Hi,
I'm having trouble on configuring the app.

```
Installed:
nodejs 6.14.3-1nodesource1
onlyoffice-documentserver 5.1.4-22
postgresql-9.0 9.0.23-1.pgdg80+2
mono-runtime 5.12.0.226-0xamarin3+debian8b1
nginx 1.6.2-5+deb8u5
rabbitmq-server 3.7.6-1
owncloud-files 10.0.8-1+1.1

Operating system:
Linux <SERVER_NAME> 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux

OnlyOffice app for OwnCloud is at release 1.3.0
```

The problem is related to a callback on downloading the empty file for configuration. When the converter call `https://www.ourcloud.it/index.php/apps/onlyoffice/empty?doc=TmlpaURaNU9MY2FUU2tKZnNxay8yVG9uTDZUdDZsdFlOYmRqZ3dZS3Azdz0/eyJhY3Rpb24iOiJlbXB0eSJ9` it retrieves this error: `{"message":"Access denied"}`
The full stacktrace is: 
```
[2018-07-25 12:17:12.033] [ERROR] nodeJS - error downloadFile:url=https://www.ourcloud.it/index.php/apps/onlyoffice/empty?doc=TmlpaURaNU9MY2FUU2tKZnNxay8yVG9uTDZUdDZsdFlOYmRqZ3dZS3Azdz0/eyJhY3Rpb24iOiJlbXB0eSJ9;attempt
    =3;code:undefined;connect:undefined;(id=conv_check_1769566394_docx)
    Error: Error response: statusCode:403 ;body:
    {"message":"Access denied"}
        at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:250:18)
        at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
        at emitTwo (events.js:106:13)
        at Request.emit (events.js:191:7)
        at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1157:10)
        at emitOne (events.js:96:13)
        at Request.emit (events.js:188:7)
        at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1079:12)
        at IncomingMessage.g (events.js:292:16)
        at emitNone (events.js:91:20)
```

Any idea?

TIA for your help.

**Comment by alexanderonlyoffice** [comment]
Hello @knife-grinder, please specify some additional information: 

1. Are ONLYOFFICE Document Server and Owncloud installed on the same machine or on different servers?
2. Send us a screenshot of ONLYOFFICE integration app address settings from Owncloud;
3. Check the accessibility of OC and DC to each other. Use wget command: 

1) `wget https://documentserver_address` on the server with OC; 
2) `wget https://owncloud_address` on the server with DS.

**Comment by knife-grinder** [comment]
They are installed on the same server and they can reach each other.

**Document Editing Service address:** https://ip_address:445/
**Document Editing Service address for internal requests from the server:** https://ip_address:445/
**Server address for internal requests from the Document Editing Service:** https://www.ourcloud.it/
**Secret key (leave blank to disable):** *******

**Comment by LinneyS** [comment]
What messages in ownCloud logs when saving connection settings?

**Comment by LinneyS** [comment]
This issue was closed due to no response.
