### ISSUE TITLE
while starting onlyoffice docker - error downloadFile

### ISSUE THREAD

**Issue by Gollus** [ONLYOFFICE/onlyoffice-owncloud#247]
Hello,
while starting onlyofficedocker I got the following error:
[2019-02-28T13:12:51.412] [ERROR] nodeJS - error downloadFile:url=https://xxx.xxx.xxx.xxx:4433/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.RD7_W06LPPrSfuPds0lmx-tshZeoXSmdaTsHKiqkL0I;attempt=3;code:null;connect:null;(id=conv_check_1850776178_docx)
Error: Error response: statusCode:404 ;body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /apps/onlyoffice/empty</pre>
</body>
</html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:250:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
Flushing stats at  Thu Feb 28 2019 13:18:58 GMT+0000 (UTC)
{ counters:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  timers: {},
  gauges: {},
  timer_data: {},
  counter_rates:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  sets: {},
  pctThreshold: [ 90 ] }

What's wrong?
Many thanks for your help!

**Comment by alexanderonlyoffice** [comment]
Hello @Gollus, please check if the address https://xxx.xxx.xxx.xxx:4433 is accessible for the Document Server. Execute command wget https://xxx.xxx.xxx.xxx:4433 from inside the container with Document Server.

**Comment by Gollus** [comment]
Hello,
thanks for your answer! I'm execute the command and got the message:
root@nextcloud:~# docker exec ONLYOFFICEDOCKER wget https://xxx.xxx.xxx.xxx:4433
--2019-03-01 10:03:25--  https://xxx.xxx.xxx.xxx:4433/
Connecting to xxx.xxx.xxx.xxx:4433... connected.
ERROR: cannot verify xxx.xxx.xxx.xxx's certificate, issued by ‘CN=xxx.xxx.xxx.xxx,OU=xxx,O=xxx,L=xxx,ST=xxx,C=xxx’:
  Self-signed certificate encountered.
To connect to xxx.xxx.xxx.xxx insecurely, use `--no-check-certificate'.

In the cofig "/etc/onlyoffice/documentserver/default.json" the parameter 
"rejectUnauthorized" ist set to "false".

What to do?

**Comment by alexanderonlyoffice** [comment]
@Gollus, it means that Document Server cannot validate SSL certificate of your ownCloud. Such situation occurs when self signed certificates are used. Specify if you have restarted Document Services after you set the parameter "rejectUnauthorized" to "false". 

Please execute also wget command from the host and if the issue is the same, you need to use CA-signed (trusted) certificates. For example, Let's encrypt CA offers free certificates that are trusted by Document Server.

**Comment by Gollus** [comment]
Hello and thanks,

now I've got a certificate from **letsencrypt** and **wget works fine**:

wget https://xxx.xxx.xxx.xxx:4433
--2019-03-11 13:25:36--  https://xxx.xxx.xxx.xxx:4433/
Resolving documentserver.vvo-online.de (xxx.xxx.xxx.xxx)... 192.168.150.71
Connecting to documentserver.vvo-online.de (xxx.xxx.xxx.xxx)|192.168.150.71|:4433... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://xxx.xxx.xxx.xxx:4433/welcome/ [following]
--2019-03-11 13:25:36--  https://xxx.xxx.xxx.xxx:4433/welcome/
Reusing existing connection to xxx.xxx.xxx.xxx:4433.
HTTP request sent, awaiting response... 200 OK
Length: 4592 (4.5K) [text/html]
Saving to: ‘index.html.1’

index.html.1        100%[===================>]   4.48K  --.-KB/s    in 0s

2019-03-11 13:25:36 (591 MB/s) - ‘index.html.1’ saved [4592/4592]

**But now I get the next error:**

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/ONLYOFFICEDOCKER/logs?stderr=1&stdout=1&tail=all: dial unix /var/run/docker.sock: connect: permission denied

What now to do?

**Comment by Gollus** [comment]
In the docker logs I found this error:

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/ONLYOFFICEDOCKER/logs?stderr=1&stdout=1&tail=all: dial unix /var/run/docker.sock: connect: permission denied

**Comment by Gollus** [comment]
I have found what's wrong:
if I logged in as a nextcloud admin, onlyoffice don't work, if I logged in as a "normal" user - it works fine - great!
