### ISSUE TITLE
Compatibility with Default encryption module

### ISSUE THREAD

**Issue by cwm77** [ONLYOFFICE/onlyoffice-owncloud#26]
While trying to open a Document a Pop-Up plops up “Error” “Download failed” “OK”.

In log file following entry is logged: 
Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.

I assume that compatibility with Default encryption module is not given yet, correct?

Nextcloud  11.0.2 (stable)

**Comment by CordlessWool** [comment]
I have the same problem

**Comment by rafilkmp3** [comment]
+1 sames here, any workarround

**Comment by e-alfred** [comment]
This seems to be a serious bug if encryption is enabled and the DocumentServer tries to download the file from the Owncloud instance. Here is the full log if I try to open a document:

```
[2017-03-27 14:58:14.999] [ERROR] nodeJS - error downloadFile:url=https://server/index.php/apps/onlyoffice/download?doc=trhrthgfdhthrhrththrh%3D%3D;attempt=1;code:undefined;connect:undefined;(id=316130081472041984)
Error: Error response: statusCode:503 ;body:
<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" >
        <head data-requesttoken="">
                <meta charset="utf-8">
                <title>
                ownCloud                </title>
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="referrer" content="never">
                <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
                <meta name="apple-itunes-app" content="app-id=543672169">
                <meta name="theme-color" content="#1d2d44">
                <link rel="icon" href="/core/img/favicon.ico">
                <link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
                <link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#1d2d44">
                                        <link rel="stylesheet" href="/core/css/styles.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/inputs.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/header.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/icons.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/fonts.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/apps.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/global.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/fixes.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/multiselect.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/mobile.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/tooltip.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/share.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/apps/files_versions/css/versions.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/apps/files_pdfviewer/css/style.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/apps/files_videoplayer/css/style.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/apps/firstrunwizard/css/colorbox.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/apps/firstrunwizard/css/firstrunwizard.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/apps/imprint/css/reference.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                        <link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=7c68a1af03e8e5edad1ba68092a1eac0">
                                                                        <script src="/core/vendor/jquery/dist/jquery.min.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/vendor/jquery-migrate/jquery-migrate.min.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/vendor/underscore/underscore.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/vendor/moment/min/moment-with-locales.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/vendor/handlebars/handlebars.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/vendor/blueimp-md5/js/md5.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/vendor/bootstrap/js/tooltip.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/vendor/backbone/backbone.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/vendor/es6-promise/dist/es6-promise.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/vendor/davclient.js/lib/client.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/placeholders.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/compatibility.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/jquery.ocdialog.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/oc-dialogs.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/js.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/l10n.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/octemplate.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/eventsource.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/config.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/search/js/search.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/oc-requesttoken.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/apps.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/mimetype.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/mimetypelist.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/vendor/snapjs/dist/latest/snap.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/vendor/backbone/backbone.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/oc-backbone.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/placeholder.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/jquery.avatar.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/apps/encryption/js/encryption.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/shareconfigmodel.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/shareitemmodel.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/sharedialogresharerinfoview.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/sharedialoglinkshareview.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/sharedialogmailview.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/sharedialogexpirationview.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/sharedialogshareelistview.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/sharedialogview.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/share.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/apps/shorten/js/script.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/apps/shorten/js/admin.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/apps/files_clipboard/js/clearClipboard.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/apps/files_pdfviewer/js/previewplugin.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/apps/files_videoplayer/js/viewer.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/apps/firstrunwizard/js/jquery.colorbox.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/apps/firstrunwizard/js/firstrunwizard.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/apps/imprint/js/reference.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/files/fileinfo.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                        <script src="/core/js/files/client.js?v=7c68a1af03e8e5edad1ba68092a1eac0"></script>
                                <meta data-imprint-position-user=""/><meta data-imprint-position-guest=""/><meta data-imprint-position-login=""/>       </head>
        <body id="body-login">
                <noscript>
        <div id="nojavascript">
                <div>
                        This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank" rel="noreferrer">enable JavaScript</a> and reload the page.          </div>
        </div>
</noscript>
                <div class="wrapper">
                        <div class="v-align">
                                                                        <header role="banner">
                                                <div id="header">
                                                        <div class="logo svg">
                                                                <h1 class="hidden-visually">
                                                                        ownCloud                                                                </h1>
                                                        </div>
                                                        <div id="logo-claim" style="display:none;"></div>
                                                </div>
                                        </header>
                                                                <ul class="error-wide">
                        <li class='error'>
                        Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.<br>
                                        </li>
        </ul>
                                <div class="push"></div><!-- for sticky footer -->
                        </div>
                </div>
                <footer role="contentinfo">
                        <p class="info">
                                <a href="https://owncloud.org" target="_blank" rel="noreferrer">ownCloud</a> – web services under your control                  </p>
                </footer>
        </body>
</html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:229:20)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1126:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1046:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

```

**Comment by JohnPerkin** [comment]
Hello!
Unfortunately current version of ONLYOFFICE does not support working with encrypted ownCloud storages. We will take this moment into consideration.

**Comment by JohnPerkin** [comment]
Hello @e-alfred!
Please update ownCloud/Nextcloud ONLYOFFICE integration app to the latest version and then follow this 
[instruction](https://doc.owncloud.org/server/latest/admin_manual/configuration_server/logging_configuration.html) to set logs level to 0. Then send logs at support@onlyoffice.com

**Comment by LinneyS** [comment]
Unfortunately if you enable the encryption with the per-user encryption keys (used by default in ownCloud/Nextcloud) ONLYOFFICE Document Server cannot open the encrypted files for editing and save them after the editing. The ONLYOFFICE section of the administrative settings page will display a notification about it. However if you set the encryption with the master key, ONLYOFFICE application will work as intended. But ownCloud/Nextcloud recommends using master encryption key only on fresh installations with no existing data, or on systems where encryption has not already been enabled.
[Encryption](https://api.onlyoffice.com/editors/owncloud#masterKey)

**Comment by Cybnate** [comment]
Onlyoffice works great but going forward encryption support at user level is needed.

Wontfix -> :-(

**Comment by chrsch** [comment]
For me and my customers won't fix is a blocker too :-(
