### ISSUE TITLE
не удалось сохранить документ

### ISSUE THREAD

**Issue by Javid907** [ONLYOFFICE/onlyoffice-owncloud#266]
Добрый день

Сначало хочу поблагодарить вас за такой продукт.

Не давно я перенес nextcloud и document server на docker и после этого когда открываю какой-либо документ у меня выходит такая ошибка 

![Screenshot from 2019-06-03 10-13-58](https://user-images.githubusercontent.com/16647132/58780117-04728900-85e9-11e9-971f-5a9efa203e77.png)

Если есть возможность прошу помочь

**Comment by Javid907** [comment]
Это Deployment что я использовал 

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: onlyoffice-app
spec:
  selector:
    matchLabels:
      app: onlyoffice-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: onlyoffice-app
    spec:
      containers:
      - name: onlyoffice-app
        image: onlyoffice/documentserver
        ports:
        - containerPort: 80
        volumeMounts:
        - name: onlyoffice-app-vol
          mountPath: /var/www/onlyoffice/Data
          subPath: onlyoffice_var_www_onlyoffice_Data
      volumes:
      - name: onlyoffice-app-vol
        persistentVolumeClaim:
          claimName: onlyoffice-app
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2

**Comment by Javid907** [comment]
И такая ошибка в логах

[2019-06-03T06:28:21.028] [ERROR] nodeJS - postData error: docId = 2625439978;url = http://cloud.anipay.az/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjU2Mywib3duZXJJZCI6Imlwc2FkbWluIiwidG9rZW4iOm51bGwsImFjdGlvbiI6InRyYWNrIn0.ADoeFDrpHXBfsLn9ION4NXTEJZSM3gyFM3Kzt55OzbY;data = {"key":"2625439978","status":1,"users":["ipsadmin"],"actions":[{"type":1,"userid":"ipsadmin"}]}
Error: Error response: statusCode:301 ;body:

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:283:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by Javid907** [comment]
Нашёл! Просто нужно было показать что nextcloud работает на https
