### ISSUE TITLE
Error: Error response: statusCode:302 ;body:

### ISSUE THREAD

**Issue by c0r3dump3d** [ONLYOFFICE/onlyoffice-owncloud#267]
Hi, I have a Nextcloud installation with version 15.0.2, and the Documentserver installation version 5.3.0 and I have this error when I try to load a document:

```
Error: Error response: statusCode:302 ;body:
at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:300:23)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```
The two installation are with https and a valid certificate, the version of onlyoffice app  is 2.1.10

I have other Nextcloud installation with version 14.0.3 with Documentserver version 5.0.7 and onlyoffice app version 2.1.10 with the same architecture and it's working. I I try to connect Nextcloud 15.0.2 with Documentserver 5.0.7 I have the same issue.

More information, if I access to Nextcloud via http the document load and edition works.

**Comment by alexanderonlyoffice** [comment]
Hello @c0r3dump3d, please send us the following log /var/log/onlyoffice/documentserver/converter/out.log to support@onlyoffice.com with a note "For technical support" in email.

**Comment by c0r3dump3d** [comment]
I have update to Nextcloud 16.0.1 and the onlyoffice app 2.3.0, but the error persist.

**Comment by c0r3dump3d** [comment]
Ohhh very nice .... I have resolve the issue, In the app configuration I need to configure the advanced option "Server address for internal requests from the Document Editing Service" with the URL of Nexclout server.
