### ISSUE TITLE
NodeJS TypeError: First argument should be a valid curve name

### ISSUE THREAD

**Issue by ingusva** [ONLYOFFICE/onlyoffice-owncloud#294]
Hello

after installing Owncloud and Onlyoffice i have problems when i activate SSL for both of them

After ssl activization self signed, i cannot start OO plugin in OC , io got error  
`Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)`

i tried 
rejectUnauthorized to false
and
verify_peer_off' => TRUE

Still error.

After that i activate certificates in certbot (lets encypt) 

Still error.
`Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be `converted.)`

https://hostname.lv:8080 - owncloud apache2
https://hostname.lv/welcome/ working Onlyoffice

Centos 7, Owncloud 10.2 , Latest OO. 

In out.err i see  nodeJS - error download

`
 [2019-11-28T14:42:51.769] [ERROR] nodeJS - error downloadFile:url=https://hostname.lv/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.Up$
TypeError: First argument should be a valid curve name
    at TypeError (native)
    at Object.createSecureContext (_tls_common.js:95:15)
    at Object.exports.connect (_tls_wrap.js:1032:48)
    at Agent.createConnection (https.js:84:22)
    at Agent.createSocket (_http_agent.js:185:26)
    at Agent.addRequest (_http_agent.js:152:10)
    at new ClientRequest (_http_client.js:174:16)
    at Object.exports.request (http.js:33:10)
    at Object.exports.request (https.js:208:15)
    at Request.start (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:751:32)
    at Request.end (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1511:10)
    at end (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:564:14)
    at Immediate.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:578:7)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

`

**Comment by ibnpetr** [comment]
Hello 

> after installing Owncloud and Onlyoffice

Could you please specify the installation type and version of the ONLYOFFICE product.

**Comment by ingusva** [comment]
installing manualy from .tar and version is 3.0.3

**Comment by ibnpetr** [comment]
> and version is 3.0.3

And what about version of the Document Server itself? 
Please try disabling certificate verification:
Open the config  /etc/onlyoffice/documentserver/local.json and set "rejectUnauthorized" to true.
Restart all services of the Document Server 
`supervisorctl restart all`

**Comment by ingusva** [comment]
Tried, same error, same problem.

**Comment by MZerg** [comment]
I have the same problem.

**Comment by MZerg** [comment]
i just add this into /etc/onlyoffice/documentserver/local.json , it's that right? 
`	  "requestDefaults": {
				"headers": {
					"userAgent": "Node.js/6.13"
				},
				"rejectUnauthorized": false
	  },`

**Comment by MZerg** [comment]
The version like this:
Nextcloud 17.0.1
ONLYOFFICE  4.0.0

**Comment by alexanderonlyoffice** [comment]
@MZerg, please try to delete the added section from local.json, then open default.json in the same folder, find 'rejectUnauthorized' parameter and set its value to false. Restart all services of the Document Server with supervisorctl restart all. 

@ingusva, specify if you restarted the services of the Document Server after disabling verification in default.json. You said that you also tried to generate SSL certificates with Let'Encrypt. Please check them on SSL Checker website [here](https://www.sslshopper.com/ssl-checker.html).

**Comment by MZerg** [comment]
Update NodeJS version can fix that error, NodeJS 10+ can use local cert, my problem is solved.
@ingusva 

Thank you @alexanderonlyoffice

**Comment by LinneyS** [comment]
Hi @ingusva 
Try updating NodeJS and tell if the error is repeated.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
