### ISSUE TITLE
documentserver receives redirect 301 code and immediately displays error 

### ISSUE THREAD

**Issue by hm400** [ONLYOFFICE/onlyoffice-owncloud#297]
When i try to create a new document in nextcloud a new tab is opened that has "Loading, please wait." with a white screen. I checked the logs on the documentserver and it has connection refused.
Im not sure if its the  document server or nginx reverse proxy causing the issue. 

```
==> /var/log/onlyoffice/documentserver/nginx.error.log <==
2020/01/06 11:08:23 [error] 747#747: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20
.0.2, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "onlyoffice", referr
er: "https://onlyoffice.example.com/welcome/"

2020/01/06 11:08:23 [error] 747#747: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20
.0.2, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "onlyoffice", referr
er: "https://onlyoffice.example.com/welcome/"

2020/01/06 11:08:24 [error] 747#747: *5 no live upstreams while connecting to upstream, client: 172.20.0.2, server: , request: 
"GET /welcome/img/icon-cross.png HTTP/1.1", upstream: "http://docservice/welcome/img/icon-cross.png", host: "onlyoffice", refer
rer: "https://onlyoffice.example.com/welcome/"
```
#Nginx reverse proxy
```
server {
	listen 443 ssl http2;
	server_name onlyoffice.example.com;
	location / {
		proxy_set_header Upgrade $http_upgrade;
	        proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://onlyoffice;
                proxy_http_version 1.1;
                #proxy_set_header Upgrade $http_upgrade; 
                proxy_set_header Connection "upgrade";  
		proxy_connect_timeout  3600s;
                proxy_read_timeout  3600s;
                proxy_send_timeout  3600s;

	}
}
```

**Comment by LinneyS** [comment]
Are there errors in the browser console when opening the editor?

**Comment by hm400** [comment]
yes there are errors in console but after reinstalling the document server i now receive error "the document could not be saved. Attaching screenshots and updated logs.
![console-tab](https://user-images.githubusercontent.com/47049792/72063631-20898780-32a8-11ea-92b8-fd779cd75451.png)
![documentserver-error](https://user-images.githubusercontent.com/47049792/72063653-2bdcb300-32a8-11ea-8dfb-ab450ec99b68.png)

**Comment by hm400** [comment]
```
[2020-01-08T01:19:43.333] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2020-01-08T01:19:43.360] [WARN] nodeJS - update cluster with 1 workers
[2020-01-08T01:19:43.372] [WARN] nodeJS - worker 764 started.
[2020-01-08T01:19:43.372] [WARN] nodeJS - update cluster with 1 workers
[2020-01-08T01:19:43.857] [WARN] nodeJS - Express server starting...
[2020-01-08T01:19:44.647] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2020-01-08T01:20:08.829] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2020-01-08T01:20:08.842] [WARN] nodeJS - update cluster with 1 workers
[2020-01-08T01:20:08.849] [WARN] nodeJS - worker 836 started.
[2020-01-08T01:20:08.849] [WARN] nodeJS - update cluster with 1 workers
[2020-01-08T01:20:09.329] [WARN] nodeJS - Express server starting...
[2020-01-08T01:20:09.986] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2020-01-08T01:32:36.164] [ERROR] nodeJS - postData error: docId = 173335947;url = http://nc.m400cloud.com/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJtaWtlIiwiZmlsZUlkIjoxMTIsImZpbGVQYXRoIjoiXC9hYmMuZG9jeCIsInNoYXJlVG9rZW4iOm51bGwsImFjdGlvbiI6InRyYWNrIn0.EWo6KBqF6-ZtcvfrVlvJR5UFLDjmxTt8XKsNgylBv8s;data = {"key":"173335947","status":1,"users":["ocxhbukekiw0_mike"],"actions":[{"type":1,"userid":"ocxhbukekiw0_mike"}]}
Error: Error response: statusCode:301 ;body:
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:301:23)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by alexanderonlyoffice** [comment]
@hm400, please specify if the issue still relevant or you have solved it.

**Comment by hm400** [comment]
Hi, the issue is with the way onlyoffice responds to the redirect 301 code.
When onlyoffice/documentserver receives the 301 code it immediately displays this message.
Everything works correctly, would like to disable this message.
![error-from -301](https://user-images.githubusercontent.com/47049792/72447145-d0686480-3782-11ea-9ad6-4010401a4657.png)
 
```
server {
	listen 80;
	listen [::]:80 default_server;
	server_name _;
	return 301 https://$host$request_uri;
}
```

**Comment by alexanderonlyoffice** [comment]
@hm400, it seems that the incorrect ownCloud address is specified on ONLYOFFICE integration app settings page. Please try to specify the address of ownCloud that is accessible for the Document Server and click on the 'Save' button.

**Comment by hm400** [comment]
@alexanderonlyoffice  thank you thank you, that was the problem. "Server address for internal requests from the Document Editing" defaulted to  http://nc.example.com  which is wrong, https://nc.example.com is correct. Also must us FQDN not docker service name.
![solution](https://user-images.githubusercontent.com/47049792/72567123-3a683300-3883-11ea-87f8-dc636f7f7cb1.png)

**Comment by hellmind** [comment]
> @alexanderonlyoffice thank you thank you, that was the problem. "Server address for internal requests from the Document Editing" defaulted to http://nc.example.com which is wrong, https://nc.example.com is correct. Also must us FQDN not docker service name. ![solution](https://user-images.githubusercontent.com/47049792/72567123-3a683300-3883-11ea-87f8-dc636f7f7cb1.png)

Dont know why the default protocol there is http, it should be https or at least, in some place tell you that he cant save document is related to that.
