### ISSUE TITLE
connector 4.2.1 not working with encryption (regression)

### ISSUE THREAD

**Issue by thommierother** [ONLYOFFICE/onlyoffice-owncloud#310]
After an upgrade to connector 4.2.1 it does not work any longer with oc encryption. I already filed this for an earlier version last year and @LinneyS made a quick fix then, but probably this code change was not included in later versions of the connector? 

See https://github.com/ONLYOFFICE/DocumentServer/issues/899 and
https://central.owncloud.org/t/onlyoffice-integration-possible-regression-in-connector-for-master-encrypted-oc/23810 for reference 

Tested on latest docserver with oc 10.4 and 10.5 RC2. Error msg on OC side:

 ```

"reqId":"Vnk6KEN7np69YX87IEzy","level":0,"time":"June 10, 2020 18:29:21","remoteAddr":"127.0.0.1","user":"admin","app":"OC\\User\\Session::validateToken","method":"PUT","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/settings\/address","message":"token e1380aed2429d25e616a219ff3f1603a1b3326ab91bd04a816c2bda1a97c67ffa049d60eb90865dbab331ddcc66c80bc2c3d2434ffbf925bba31469d73e937bc with token id 106650 found, validating"}
{"reqId":"Vnk6KEN7np69YX87IEzy","level":0,"time":"June 10, 2020 18:29:21","remoteAddr":"127.0.0.1","user":"admin","app":"OC\\User\\Session::validateToken","method":"PUT","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/settings\/address","message":"token e1380aed2429d25e616a219ff3f1603a1b3326ab91bd04a816c2bda1a97c67ffa049d60eb90865dbab331ddcc66c80bc2c3d2434ffbf925bba31469d73e937bc with token id 106650 found, validating"}
{"reqId":"Vnk6KEN7np69YX87IEzy","level":1,"time":"June 10, 2020 18:29:21","remoteAddr":"127.0.0.1","user":"admin","app":"onlyoffice","method":"PUT","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/settings\/address","message":"Select demo: false"}
{"reqId":"Vnk6KEN7np69YX87IEzy","level":1,"time":"June 10, 2020 18:29:21","remoteAddr":"127.0.0.1","user":"admin","app":"onlyoffice","method":"PUT","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/settings\/address","message":"SetDocumentServerUrl: https:\/\/docs.netzwissen.de\/"}
{"reqId":"Vnk6KEN7np69YX87IEzy","level":1,"time":"June 10, 2020 18:29:21","remoteAddr":"127.0.0.1","user":"admin","app":"onlyoffice","method":"PUT","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/settings\/address","message":"SetDocumentServerInternalUrl: "}
{"reqId":"Vnk6KEN7np69YX87IEzy","level":1,"time":"June 10, 2020 18:29:21","remoteAddr":"127.0.0.1","user":"admin","app":"onlyoffice","method":"PUT","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/settings\/address","message":"Set secret key"}
{"reqId":"Vnk6KEN7np69YX87IEzy","level":1,"time":"June 10, 2020 18:29:21","remoteAddr":"127.0.0.1","user":"admin","app":"onlyoffice","method":"PUT","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/settings\/address","message":"SetStorageUrl: "}
{"reqId":"Vnk6KEN7np69YX87IEzy","level":3,"time":"June 10, 2020 18:29:21","remoteAddr":"127.0.0.1","user":"admin","app":"onlyoffice","method":"PUT","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/settings\/address","message":"CommandRequest on check error: {\"Exception\":\"Exception\",\"Message\":\"Error occurred in the document service: Invalid token\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/onlyoffice\\\/lib\\\/documentservice.php(305): OCA\\\\Onlyoffice\\\\DocumentService->ProcessCommandServResponceError(6)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/onlyoffice\\\/controller\\\/settingscontroller.php(283): OCA\\\\Onlyoffice\\\\DocumentService->CommandRequest('version')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/onlyoffice\\\/controller\\\/settingscontroller.php(168): OCA\\\\Onlyoffice\\\\Controller\\\\SettingsController->checkDocServiceUrl()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Onlyoffice\\\\Controller\\\\SettingsController->SaveAddress('https:\\\/\\\/docs.ne...', '', '', 'WCXb2byYtBf8', false)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Onlyoffice\\\\Controller\\\\SettingsController), 'saveAddress')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Onlyoffice\\\\Controller\\\\SettingsController), 'saveAddress')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('SettingsControl...', 'saveAddress', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(916): OC\\\\Route\\\\Router->match('\\\/apps\\\/onlyoffic...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/onlyoffice\\\/lib\\\/documentservice.php\",\"Line\":338}"}
```

**Comment by LinneyS** [comment]
Hi @thommierother 
I have installed ownCloud 10.4.0 (stable), ownCloud ONLYOFFICE integration app 4.2.1, ONLYOFFICE Document Server 5.5.0.165
Created several files
Enabled encryption https://doc.owncloud.com/server/admin_manual/configuration/files/encryption/encryption_configuration.html#enabling-master-key-based-encryption-from-the-command-line

I can edit old encrypted files and create new files well.

And I have reviewed the changes between 4.2.1 and 4.1.3 and there are no open / save edits that could affect encryption.

**Comment by LinneyS** [comment]
`Error occurred in the document service: Invalid token` in your log says the JWT secret is wrong

**Comment by thommierother** [comment]
ok, I'll have a look again, thanks for the re-check
