### ISSUE TITLE
Owncloud have not access on onlyoffice when you activate the secrets.

### ISSUE THREAD

**Issue by rboufenghour** [ONLYOFFICE/onlyoffice-owncloud#311]
We have two infrastrature , one with owncloud 10.4.1 with onlyoffice 4.2.1 and nextcloud 18.0.4  with onlyoffice 4.2.0

When we activate the secrets in onlyoffice, we get an error on the owncloud side (and not on the nextcloud side) of the type : 
"GetConvertedUri on check error: An error occurred in the document service: Error while downloading the document file to be converted"  

In onlyoffice we have this error : 
/var/log/onlyoffice/documentserver/converter/out.log

[2020-06-11T12:29:56.240] [ERROR] nodeJS - error downloadFile:url=https://xxxxxxxxxxxxxx/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.IBeEoE6TRF6FZ5Baz5-mpYKlZQrCC2eBBlIu7YwTT5g;attempt=2;code:null;connect:null;(id=conv_check_407718000_docx)
Error: Error response: statusCode:403 ;body:
<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="fr" >
	<head data-requesttoken="WCN3ByFXbF0gHTQvGWcWfw4CN2MvGU0FE2QkS3xKd38=:aaFWqe57bqvytRSJjkv6bUxN84TsI3C53U/+xztd/s8=">
		<meta charset="utf-8">
		<title>
		ownCloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="referrer" content="never">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
					<meta name="apple-itunes-app" content="app-id=543672169">
				<meta name="theme-color" content="#1d2d44">
		<link rel="icon" href="/core/img/favicon.ico">
		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#1d2d44">
					<link rel="stylesheet" href="/core/vendor/select2/select2.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/styles.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/inputs.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/header.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/icons.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/fonts.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/apps.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/global.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/fixes.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/multiselect.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/mobile.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/tooltip.css?v=6712ffd49cea181b6351e44fd346bf13">
					<link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=6712ffd49cea181b6351e44fd346bf13">
									<script src="/core/js/oc.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/jquery/dist/jquery.min.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/jquery-migrate/jquery-migrate.min.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/underscore/underscore.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/moment/min/moment-with-locales.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/handlebars/handlebars.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/blueimp-md5/js/md5.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/bootstrap/js/tooltip.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/backbone/backbone.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/es6-promise/dist/es6-promise.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/davclient.js/lib/client.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/clipboard/dist/clipboard.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/bowser/src/bowser.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/jquery.ocdialog.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/oc-dialogs.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/js.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/l10n.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/l10n/fr.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/octemplate.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/eventsource.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/config.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/search/js/search.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/oc-requesttoken.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/apps.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/mimetype.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/mimetypelist.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/snapjs/dist/latest/snap.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/vendor/select2/select2.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/oc-backbone.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/oc-backbone-webdav.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/placeholder.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/jquery.avatar.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/backgroundjobs.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/files/fileinfo.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					<script src="/core/js/files/client.js?v=6712ffd49cea181b6351e44fd346bf13"></script>
					</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			Cette application requiert JavaScript pour fonctionner correctement. Veuillez <a href="http://enable-javascript.com/" target="_blank" rel="noreferrer">activer JavaScript</a> et recharger la page.		</div>
	</div>
</noscript>
		<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo">
								<h1 class="hidden-visually">
									ownCloud								</h1>
							</div>
							<div id="logo-claim" style="display:none;"></div>
						</div>
					</header>
								<ul>
	<li class='error'>
		Accès interdit<br>
		<p class='hint'></p>
	</li>
</ul>
				<div class="push"></div>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://owncloud.org" target="_blank" rel="noreferrer">ownCloud</a> &ndash; Un endroit sûr pour toutes vos données			</p>
		</footer>
	</body>
</html>

    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by thommierother** [comment]
See https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/310, maybe both have the same root cause?

The old issue with encryption which I already filed in January (which was fixed by Sergejy Linnick with a quick fix) was

https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/296

and commit 
https://github.com/ONLYOFFICE/onlyoffice-owncloud/commit/10df64b3a7c3b91c2222b3e27a82293194416ea8

Maybe the code change was not included in later builds?

**Comment by thommierother** [comment]
is anyone working on this? No progess for weeks .....
