### ISSUE TITLE
when open document file fail and the log report Parse Error

### ISSUE THREAD

**Issue by lov0** [ONLYOFFICE/onlyoffice-owncloud#322]
Hi ！ I have problem  with this app，My environment is made up of   Owncloud（tar,version10.3.0）  with onlyOffice（docker,the laster),i can create new file  and save it ，but i can’t  open existed  document files, when i open a  existed file,the  windows reported   
downloading fail, the  logs `docker logs exe89dweqq0` `[2020-08-26T11:22:12.398] [ERROR] nodeJS - error downloadFile:url=http://192.168.1.104:38393/index.php/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjUxOTYwLCJ1c2VySWQiOiJsaW5xaWFuZyIsInNoYXJlVG9rZW4iOm51bGwsImFjdGlvbiI6ImRvd25sb2FkIn0.1JF7q6nzUcseQWeO2FPhkXKeTI2zPapefSLWbNCfsSQ;attempt=2;code:HPE_INVALID_CONSTANT;connect:null;(id=1996527678)
Error: Parse Error
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
`   ,I've tried this #241    but it doesn't work 

Attach configs ,
owncloud:
`
/var/www/html/config/config.php
<?php
$CONFIG = array (
  'instanceid' => 'ocpg27jym54f',
  'passwordsalt' => 'kdFMrWKrV+cRnZwiSAQrybPBFy8icd',
  'secret' => 'Pu7TB2Fz8a/PYbAmZoONj58RbUCmp/AB1LjBFImlBBb+nFTL',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '176.122.xxx.xxx',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '10.3.0.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_linqiang',
  'dbpassword' => 'neDLhm13j2c1Q9ZUbqmxJj2pYJan6g',
  'logtimezone' => 'UTC',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/apps-external',
      'url' => '/apps-external',
      'writable' => true,
    ),
  ),
  'installed' => true,
);
`
onlyOffice:
`/etc/onlyoffice/documentserver/local.json
            "outbox": false
          },
          "browser": false
        },
        "inbox": {
          "header": "AuthorizationJwt"
        },
        "outbox": {
          "header": "AuthorizationJwt"
        }
      },
      "secret": {
        "inbox": {
          "string": "secret"
        },        "outbox": {
          "string": "secret"
        },
        "session": {
          "string": "secret"
        }
      }
    }
  },
  "rabbitmq": {
    "url": "amqp://guest:guest@localhost"
  }
}
`
I've set up the privateIP in the advanced options, the public IP in the first document server input 
I don't have a domain and I'm just use public IP and I'm using HTTP instead of HTTPS. Does that matter?

**Comment by lov0** [comment]
I'm sorry about my poor typogr,to summarize my question:

1.ownCloud(10.3.0) +onlyOffice(docker,the laster)

2.can  create new document file and save it ,but can't open existed files

3.when open  existed files ,the windows reproted  downloading fail

4.the onlyOffice container logs `docker logs exe89dweqq0 [2020-08-26T11:22:12.398] [ERROR] nodeJS - error 
downloadFile:url=http://192.168.1.104:38393/index.php/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjUxOTYwLCJ1c2VySWQiOiJsaW5xaWFuZyIsInNoYXJlVG9rZW4iOm51bGwsImFjdGlvbiI6ImRvd25sb2FkIn0.1JF7q6nzUcseQWeO2FPhkXKeTI2zPapefSLWbNCfsSQ;attempt=2;code:HPE_INVALID_CONSTANT;connect:null;(id=1996527678) Error: Parse Error at Socket.socketOnData (_http_client.js:442:20) at Socket.emit (events.js:198:13) at addChunk (_stream_readable.js:287:12) at readableAddChunk (_stream_readable.js:268:11) at Socket.Readable.push (_stream_readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:94:17)`


5.already tried this #241  but it doesn't work

6.`/var/www/html/config/config.php
'ocpg27jym54f', 'passwordsalt' => 'kdFMrWKrV+cRnZwiSAQrybPBFy8icd', 'secret' => 'Pu7TB2Fz8a/PYbAmZoONj58RbUCmp/AB1LjBFImlBBb+nFTL', 'trusted_domains' => array ( 0 => 'localhost', 1 => '176.122.xxx.xxx', ), 'datadirectory' => '/var/www/html/data', 'overwrite.cli.url' => 'http://localhost', 'dbtype' => 'mysql', 'version' => '10.3.0.4', 'dbname' => 'owncloud', 'dbhost' => 'localhost', 'dbtableprefix' => 'oc_', 'mysql.utf8mb4' => true, 'dbuser' => 'oc_linqiang', 'dbpassword' => 'neDLhm13j2c1Q9ZUbqmxJj2pYJan6g', 'logtimezone' => 'UTC', 'apps_paths' => array ( 0 => array ( 'path' => '/var/www/html/apps', 'url' => '/apps', 'writable' => false, ), 1 => array ( 'path' => '/var/www/html/apps-external', 'url' => '/apps-external', 'writable' => true, ), ), 'installed' => true, ); `


7.` onlyOffice: `/etc/onlyoffice/documentserver/local.json "outbox": false }, "browser": false }, "inbox": { "header": "AuthorizationJwt" }, "outbox": { "header": "AuthorizationJwt" } }, "secret": { "inbox": { "string": "secret" }, "outbox": { "string": "secret" }, "session": { "string": "secret" } } } }, "rabbitmq": { "url": "amqp://guest:guest@localhost" } } `

8.don't have a domain and just use public IP and use HTTP instead of HTTPS.

9.already  set up the privateIP in the advanced options, the public IP in the first document server input
