### ISSUE TITLE
owncloud 10.8.0.4 - onlyoffice upgrade to 7.3.1 fail

### ISSUE THREAD

**Issue by esosan** [ONLYOFFICE/onlyoffice-owncloud#368]
Hello, I have some trouble with the update to 7.3.1.

OS :Ubuntu 18.04.4
Owncloud version : 10.8.0.4
Onlyoffice version : 6.4.2

```
2022-01-20T07:35:36+01:00 Set log level to debug
2022-01-20T07:35:36+01:00 Turned on maintenance mode
2022-01-20T07:35:36+01:00 Repair step: Upgrade app code from the marketplace
2022-01-20T07:35:36+01:00 Repair step: Repair MySQL database engine
2022-01-20T07:35:36+01:00 Repair step: Repair MySQL collation
2022-01-20T07:35:36+01:00 Repair info: All tables already have the correct collation -> nothing to do
2022-01-20T07:35:36+01:00 Repair step: Repair SQLite autoincrement
2022-01-20T07:35:36+01:00 Repair step: Repair orphaned reshare
2022-01-20T07:35:36+01:00 Repair step: Repair duplicate entries in oc_lucene_status
2022-01-20T07:35:36+01:00 Repair info: lucene_status table does not exist -> nothing to do
2022-01-20T07:35:36+01:00 Updating database schema
2022-01-20T07:35:36+01:00 Updated database
2022-01-20T07:35:37+01:00 Updating <onlyoffice> ...
An unhandled exception has been thrown:
ParseError: syntax error, unexpected end of file in /var/www/html/owncloud_cryms/owncloud/apps-external/onlyoffice/lib/mimerepair.php:226
Stack trace:
#0 [internal function]: OC\Autoloader->load('OCA\\Onlyoffice\\...')
#1 [internal function]: spl_autoload_call('OCA\\Onlyoffice\\...')
#2 /var/www/html/owncloud_cryms/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(88): ReflectionClass->__construct('OCA\\Onlyoffice\\...')
#3 /var/www/html/owncloud_cryms/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(110): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Onlyoffice\\...')
#4 /var/www/html/owncloud_cryms/owncloud/lib/private/ServerContainer.php(79): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Onlyoffice\\...')
#5 /var/www/html/owncloud_cryms/owncloud/lib/private/Repair.php(103): OC\ServerContainer->query('OCA\\Onlyoffice\\...')
#6 /var/www/html/owncloud_cryms/owncloud/lib/private/legacy/app.php(1029): OC\Repair->addStep('OCA\\Onlyoffice\\...')
#7 /var/www/html/owncloud_cryms/owncloud/lib/private/legacy/app.php(987): OC_App::executeRepairSteps('onlyoffice', Array)
#8 /var/www/html/owncloud_cryms/owncloud/lib/private/Updater.php(347): OC_App::updateApp('onlyoffice')
#9 /var/www/html/owncloud_cryms/owncloud/lib/private/Updater.php(273): OC\Updater->doAppUpgrade()
#10 /var/www/html/owncloud_cryms/owncloud/lib/private/Updater.php(114): OC\Updater->doUpgrade('10.8.0.4', '10.8.0.4')
#11 /var/www/html/owncloud_cryms/owncloud/core/Command/Upgrade.php(269): OC\Updater->upgrade()
#12 /var/www/html/owncloud_cryms/owncloud/lib/composer/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/owncloud_cryms/owncloud/lib/composer/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/owncloud_cryms/owncloud/lib/composer/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/owncloud_cryms/owncloud/lib/composer/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/owncloud_cryms/owncloud/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/owncloud_cryms/owncloud/console.php(116): OC\Console\Application->run()
#18 /var/www/html/owncloud_cryms/owncloud/occ(11): require_once('/var/www/html/o...')
#19 {main}```

**Comment by GyuriT** [comment]
Hi,
I had the same problem. For me it caused by the [heredoc syntax](https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes) used in mimerepair.php is not compatible with PHP7.2. The solution is removing all spaces/tabs in front of `MTLC;` in line 222.
So change in `.../onlyoffice/lib/mimerepair.php` from:
```    private function generateMimeTypeListContent($aliases, $files, $themes) {
        $aliasesJson = \json_encode($aliases, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        $filesJson = \json_encode($files, JSON_PRETTY_PRINT);
        $themesJson = \json_encode($themes, JSON_PRETTY_PRINT);

        $content = <<< MTLC
            /**
            * This file is automatically generated
            * DO NOT EDIT MANUALLY!
            *
            * You can update the list of MimeType Aliases in config/mimetypealiases.json
            * The list of files is fetched from core/img/filetypes
            * To regenerate this file run ./occ maintenance:mimetype:update-js
            */
            OC.MimeTypeList={
                aliases: $aliasesJson,
                files: $filesJson,
                themes: $themesJson
            };
            MTLC;

        return $content;
    }
```
to
```    private function generateMimeTypeListContent($aliases, $files, $themes) {
        $aliasesJson = \json_encode($aliases, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        $filesJson = \json_encode($files, JSON_PRETTY_PRINT);
        $themesJson = \json_encode($themes, JSON_PRETTY_PRINT);

        $content = <<< MTLC
            /**
            * This file is automatically generated
            * DO NOT EDIT MANUALLY!
            *
            * You can update the list of MimeType Aliases in config/mimetypealiases.json
            * The list of files is fetched from core/img/filetypes
            * To regenerate this file run ./occ maintenance:mimetype:update-js
            */
            OC.MimeTypeList={
                aliases: $aliasesJson,
                files: $filesJson,
                themes: $themesJson
            };
MTLC;

        return $content;
    }
```
And run `sudo -u www-data php occ ugrade`.

**Comment by esosan** [comment]
hi @GyuriT, I have tried your solution and it's work.
As a side effect the integrity check fails (obviously), after the update I restored the original file and everything seems to work.
