### ISSUE TITLE
Connect Onlyoffice with owncloud

### ISSUE THREAD

**Issue by samuraiohelson** [ONLYOFFICE/onlyoffice-owncloud#386]
Hi. Please help me, when i try to connect owncloud with onlyoffice i got this error:

"Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 7.1.1.23)"

Logs from the owncloud.log file:

####################################Log start############################
{"reqId":"8yDJpC0dKJF57RfLgYeT","level":3,"time":"2022-08-02T12:55:35+00:00","remoteAddr":"192.168.6.88","user":"--","app":"PHP","method":"GET","url":"\/index.php\/apps\/onlyoffice\/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.KbU8VCjjP4cgDTKu-xSqqsmqwm99pxFC9PfWbdDQJ4M","message":"file_get_contents(\/var\/www\/html\/owncloud\/apps\/onlyoffice\/assets\/en-US\/new.docx): failed to open stream: No such file or directory at \/var\/www\/html\/owncloud\/apps\/onlyoffice\/controller\/callbackcontroller.php#356"}
{"reqId":"Aj4TnPA1wVqYUNQeDYMh","level":3,"time":"2022-08-02T12:55:36+00:00","remoteAddr":"192.168.6.88","user":"--","app":"PHP","method":"GET","url":"\/index.php\/apps\/onlyoffice\/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.KbU8VCjjP4cgDTKu-xSqqsmqwm99pxFC9PfWbdDQJ4M","message":"file_get_contents(\/var\/www\/html\/owncloud\/apps\/onlyoffice\/assets\/en-US\/new.docx): failed to open stream: No such file or directory at \/var\/www\/html\/owncloud\/apps\/onlyoffice\/controller\/callbackcontroller.php#356"}
{"reqId":"isoFiwLMPQb1NJ2MXUNP","level":3,"time":"2022-08-02T12:55:37+00:00","remoteAddr":"192.168.6.88","user":"--","app":"PHP","method":"GET","url":"\/index.php\/apps\/onlyoffice\/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.KbU8VCjjP4cgDTKu-xSqqsmqwm99pxFC9PfWbdDQJ4M","message":"file_get_contents(\/var\/www\/html\/owncloud\/apps\/onlyoffice\/assets\/en-US\/new.docx): failed to open stream: No such file or directory at \/var\/www\/html\/owncloud\/apps\/onlyoffice\/controller\/callbackcontroller.php#356"}
{"reqId":"62HuuHnaRddt8jkPzEds","level":3,"time":"2022-08-02T12:55:39+00:00","remoteAddr":"192.168.8.232","user":"administrator","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings\/address","message":"GetConvertedUri on check error: {\"Exception\":\"Exception\",\"Message\":\"Error occurred in the document service: Error while downloading the document file to be converted.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/onlyoffice\\\/lib\\\/documentservice.php(94): OCA\\\\Onlyoffice\\\\DocumentService->ProcessConvServResponceError()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/onlyoffice\\\/lib\\\/documentservice.php(437): OCA\\\\Onlyoffice\\\\DocumentService->GetConvertedUri()\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/onlyoffice\\\/controller\\\/settingscontroller.php(172): OCA\\\\Onlyoffice\\\\DocumentService->checkDocServiceUrl()\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(170): OCA\\\\Onlyoffice\\\\Controller\\\\SettingsController->SaveAddress()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(928): OC\\\\Route\\\\Router->match()\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/onlyoffice\\\/lib\\\/documentservice.php\",\"Line\":236}"}

####################################Log End#############################

**Comment by SergeyKorneyev** [comment]
Hi,
It looks like the submodule with empty documents is missing in your connector installation. Could you try downloading it with 
`git submodule update --init` ?
