### ISSUE TITLE
File download error with SMB/CIFS External storage

### ISSUE THREAD

**Issue by danielepercivaldi** [ONLYOFFICE/onlyoffice-owncloud#51]
Environment:
oc 9.1.5
onlyoffice document server 4.3.2 
onlyoffice integration app 1.0.2
External Storage app 0.6.0

Issue:
When you open a file from a SMB/CIFS external storage defined by the oc admin with authentication option "Session User" onlyoffice get "Download Error" message.
Same file, same external storage with "fixed user authentication" option, it works.

It seems that the app is not able to get session user credentials (using LDAP against active directory).

Here the ownCloud log when you try to open a file on SMB/CIFS external storage with session authentication (note that user is "--"):

{"reqId":"faCyDYYvWRFpwAN7bU+L","remoteAddr":"172.17.0.1","app":"onlyoffice","message":"Files for download not found: 2485058","level":1,"time":"Wed, 26 Apr 2017 22:12:54 +0200","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=bzNsZjFpbzg4SGw1aDFXWFV2eERkR0NScWJNZTVLNUpJRldTSGlBNmt0UT0\/eyJmaWxlSWQiOjI0ODUwNTgsIm93bmVySWQiOiJwcmMiLCJhY3Rpb24iOiJkb3dubG9hZCJ9","user":"--"}

Below the log in Onlyoffice converter/out.log:

[2017-04-25 12:21:22.887] [ERROR] nodeJS - error downloadFile:url=https://xxx.xxxxx.xx/index.php/apps/onlyoffice/download?doc=dk5GYjNDdS9YK2hmWkFQWnZMbGVlWFNoSkJBajBsTG55OHpIUnBKTTZnWT0/eyJmaWxlSWQiOjExMTE5ODYsIm93bmVySWQiOiJwcmMiLCJhY3Rpb24iOiJkb3dubG9hZCJ9;attempt=1;code:undefined;connect:undefined;(id=111198614931201232)
Error: Error response: statusCode:404 ;body:
{"message":"Files not found"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:234:20)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
[2017-04-25 12:21:24.188] [ERROR] nodeJS - error downloadFile:url=https://xxx.xxxxx.xx/index.php/apps/onlyoffice/download?doc=dk5GYjNDdS9YK2hmWkFQWnZMbGVlWFNoSkJBajBsTG55OHpIUnBKTTZnWT0/eyJmaWxlSWQiOjExMTE5ODYsIm93bmVySWQiOiJwcmMiLCJhY3Rpb24iOiJkb3dubG9hZCJ9;attempt=2;code:undefined;connect:undefined;(id=111198614931201232)
Error: Error response: statusCode:404 ;body:
{"message":"Files not found"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:234:20)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
[2017-04-25 12:21:25.468] [ERROR] nodeJS - error downloadFile:url=https://xxx.xxxxx.xx/index.php/apps/onlyoffice/download?doc=dk5GYjNDdS9YK2hmWkFQWnZMbGVlWFNoSkJBajBsTG55OHpIUnBKTTZnWT0/eyJmaWxlSWQiOjExMTE5ODYsIm93bmVySWQiOiJwcmMiLCJhY3Rpb24iOiJkb3dubG9hZCJ9;attempt=3;code:undefined;connect:undefined;(id=111198614931201232)
Error: Error response: statusCode:404 ;body:
{"message":"Files not found"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:234:20)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

**Comment by taut98** [comment]
Is your OnlyOffice saving documents you changed?
I have the Problem with my NC that OnlyOffice doesnt save.

Marked from @JohnPerkin as official Bug.

**Comment by danielepercivaldi** [comment]
Hi @taut98 
Yes, when I open a file on SMB/CIFS external storage I can save it. Of course, I have to set up the external storage with "Fixed authentication".

**Comment by JohnPerkin** [comment]
Hello!
ONLYOFFICE ownCloud/Nextcloud integration app was developed to work with documents in ownCloud/NextCloud instances and we do not  guarantee its working with any external storages.
Thank you for your feedback, we will take it into consideration.

**Comment by taut98** [comment]
@danielepercivaldi Hey, did you make any configuration steps at your onlyoffice instance?
What do you mean with Fixed Authentification? Global Authentificationparameters?

**Comment by danielepercivaldi** [comment]
Hi @taut98 .
For onlyoffice, nothing strange. I followed docker installation instructions you can read on onlyoffice site and the line below:
docker run --restart=always -i -t -d -p 8081:80 -v /opt/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  onlyoffice/documentserver

For "Fixed authentication" I mean defining external storage entering user and password in admin control panel (see attachement). If you use "Session user authentication" onlyoffice does not work.

![immagine](https://cloud.githubusercontent.com/assets/8720648/25484553/bd4e8c08-2b5a-11e7-8508-cb3f0367c76b.png)

**Comment by xadhoom** [comment]
confirmed. but if you save them into the db instead of the session, it works.
Not optimal, but good enough for testing it.

**Comment by danielepercivaldi** [comment]
Yes, I know, it works that way.
 You know, @xadhoom , it means that I have to setup SMB/CIFS External storage with specific username and password, while I would like to grant the access to the current user depending on its own privileges.

It seems , in reference to @JohnPerkin comment, that this situation is not supported by onlyoffice app.

**Comment by xadhoom** [comment]
@danielepercivaldi no, you can save the user credentials on the DB instead of session and works. this is different from having a single static user for connecting the share from nextCloud. This is the "Log-in credentials, save in database" selection, instead of "Log-in credentials, save in session".

I think you're referring to the "Username and password" selection

**Comment by danielepercivaldi** [comment]
@xadhoom , I haven't got "Log-in credentials, save in database" option: using oc 9.1.6 and not nc 1x.x.x.

**Comment by xadhoom** [comment]
whops, ok so, I missed that, sorry. I'm using latest nextcloud.

**Comment by Roumanille** [comment]
No user / password settings work with the use of network storage !!
Have you found another solution?

**Comment by flaminestone** [comment]
@Roumanille Can't reproduce this issue.
ownCloud 9.1.5 (stable)
onlyoffice/documentserver:4.3.2.3 
onlyoffice integration app  1.1.6
External Storage app 0.6.0

**Comment by flaminestone** [comment]
@Roumanille Can't reproduce this issue.
ownCloud 9.1.5 (stable)
onlyoffice/documentserver:4.3.2.3
onlyoffice integration app 1.1.6
External Storage app 0.6.0

**Comment by Roumanille** [comment]
NextCloud 12.0.4
OnlyOffice  integration app 1.1.6
External Storage Support app 1.3.0
LDAP user and group backed app 1.2.1
Onlyoffice/document server external linux : last version

Opening a .docx or .xlsx file works, but converting .doc or .xls files does not work on the network storage associated with users.  On the folders not networks it works !

Thank's

**Comment by alexanderonlyoffice** [comment]
Hello @danielepercivaldi, please note that with authentication option "Session User" it does not work. Please follow this [link](https://api.onlyoffice.com/editors/owncloud#externalStorage) to find a description of the issue in Known Issues sections.
