### ISSUE TITLE
I cannot Edit files with Onlyoffice and Nextcloud 12 and Onlyoffice App 1.0.5

### ISSUE THREAD

**Issue by darkhedie** [ONLYOFFICE/onlyoffice-owncloud#79]
Hi

Since many hours, im trying to get onlyoffice working with nextcloud. 
I have onlyoffice running as a docker container on port -p 444:443

I also run an apache as reverse proxy. 

here is my configuration: 

`
<VirtualHost *:443>

        LoadModule setenvif_module modules/mod_setenvif.so

        ServerName abc.domain.com
        SSLEngine On
        SSLProxyEngine On
        ProxyPreserveHost On
        ProxyRequests Off
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerExpire off
        SSLInsecureRenegotiation on
        SSLProxyVerify none
        SSLVerifyClient none

        SSLProtocol all -SSLv2

        SSLCipherSuite ALL:!ADH:!EXPORT:!SSLv2:RC4+RSA:+HIGH:+MEDIUM

        SSLCertificateFile      /etc/letsencrypt/live/abc.domain.com/fullchain.pem
        SSLCertificateChainFile /etc/letsencrypt/live/abc.domain.com/fullchain.pem
        SSLCertificateKeyFile   /etc/letsencrypt/live/abc.domain.com/privkey.pem

        SSLProxyCheckPeerName off
        #RequestHeader unset Accept-Encoding
        #ProxyPass / https://192.168.50.20:444/
        #ProxyPassReverse / https://192.168.50.20:444/

        RequestHeader setifempty X-Forwarded-Proto https
        ProxyAddHeaders Off

        ProxyPassMatch (.*)(\/websocket)$ "wss://192.168.50.20/$1$2"

        RequestHeader unset Accept-Encoding
        ProxyPass / https://192.168.50.20:444/
        ProxyPassReverse / https://192.168.50.20:444/
        #ProxyPass "/websocket" "ws://192.168.50.20:444/websocket"
        #ProxyPassReverse "/websocket" "ws://192.168.50.20:444/websocket"

        <proxy *>
                AddDefaultCharset off
                Order Allow,Deny
                Allow from all
        </proxy>

</VirtualHost>
`

Unfortunately, i alway get the following image: 

![0ad06d52-0572-11e7-896b-cb4151085262](https://user-images.githubusercontent.com/6323250/27009982-26c08778-4e9b-11e7-90ee-59be45b375b7.PNG)

I defenitley dont havy any more ideas. 
I would be very happy if someone could help me. 

Thank you.

**Comment by e-alfred** [comment]
I have the very same problem with NC 12 and the 1.0.5 app and the latest Onlyoffice docker image. Everything worked well with 1.0.4.

Here is the out.log from the container:

```
[2017-06-11 15:33:38.199] [ERROR] nodeJS - postData error: docId = 241583149718878128;url = https://server/owncloud/apps/onlyoffice/track?doc=M2Q5WlhHZGlhdWZlZnluZGVqaHhKaDJJOXpwLzlVQW0zejVqSEJwWTRZVT0/eyJmaWxlSWQiOjI0MTU4Mywib3duZXJJZCI6ImFsZnJlZCIsImFjdGlvbiI6InRyYWNrIn0%3D;data = {"key":"241583149718878128","status":1,"users":["alfred"],"actions":[{"type":1,"userid":"alfred"}]}
Error: Error response: statusCode:403 ;body:
{"message":"Access deny"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:260:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
[2017-06-11 15:33:42.590] [ERROR] nodeJS - changesError: docId = 241583149718878128 Error: Uncaught TypeError: Cannot read property 'canDownload' of undefined Script: https://server/2017-06-02-12-46/web-apps/apps/documenteditor/main/app.js Line: 8:343888 userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 platform: Linux x86_64 StackTrace: TypeError: Cannot read property 'canDownload' of undefined
    at r.show (https://server/2017-06-02-12-46/web-apps/apps/documenteditor/main/app.js:8:343888)
    at r.onBtnMenuToggle (https://server/2017-06-02-12-46/web-apps/apps/documenteditor/main/app.js:8:350681)
    at c (https://server/2017-06-02-12-46/web-apps/apps/documenteditor/main/app.js:8:113668)
    at r.trigger (https://server/2017-06-02-12-46/web-apps/apps/documenteditor/main/app.js:8:112923)
    at r.toggle (https://server/2017-06-02-12-46/web-apps/apps/documenteditor/main/app.js:8:224825)
    at r.showMenu (https://server/2017-06-02-12-46/web-apps/apps/documenteditor/main/app.js:8:353479)
    at r.<anonymous> (https://server/2017-06-02-12-46/web-apps/apps/documenteditor/main/app.js:8:1332062)
    at HTMLButtonElement.a (https://server/2017-06-02-12-46/web-apps/apps/documenteditor/main/app.js:8:191420)
    at HTMLButtonElement.dispatch (https://server/2017-06-02-12-46/web-apps/apps/documenteditor/main/app.js:8:70190)
    at HTMLButtonElement.m.handle (https://server/2017-06-02-12-46/web-apps/apps/documenteditor/main/app.js:8:68091)
[2017-06-11 15:36:41.067] [ERROR] nodeJS - postData error: docId = 26024114962460021;url = https://server/owncloud/apps/onlyoffice/track?doc=ZGlubHJ3NFR1dGQwcE5aYzNsamk2QkU5NEtzY25MZjdhYlVQa1FhaVhyND0/eyJmaWxlSWQiOjI2MDI0MSwib3duZXJJZCI6ImFsZnJlZCIsImFjdGlvbiI6InRyYWNrIn0%3D;data = {"key":"26024114962460021","status":1,"users":["alfred"],"actions":[{"type":1,"userid":"alfred"}]}
Error: Error response: statusCode:403 ;body:
{"message":"Access deny"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:260:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)

```

**Comment by Ramalama2** [comment]
Same here since 1.0.5
1.0.4 worked well

**Comment by e-alfred** [comment]
I set the secret to default ("secret" in default.json and empty in the Nextcloud app), then everything works well. After inserting them again the problem shown abover comes back.

As a workaround I removed the secret key and put an ipfilter for my domain into the default.json file. This works, but it is just a workaround.

**Comment by JohnPerkin** [comment]
@Ramalama2 
Did you specify **Server address for internal requests from the Document Editing Service** in the Admin settings page? You may try to do it.

**Comment by JohnPerkin** [comment]
@e-alfred 
You may follow this [instruction](https://doc.owncloud.org/server/latest/admin_manual/configuration_server/logging_configuration.html) to set logs level to 0. Then post logs here or send at support@onlyoffice.com

**Comment by darkhedie** [comment]
@JohnPerkin how can i access the admin page of the document server?
If you mean the section in the nextcloud admin page, then yes.

**Comment by JohnPerkin** [comment]
@darkhedie 
You are right, I mean Admin settings page in NextCloud. Document Server does not have administrator's settings.

**Comment by darkhedie** [comment]
@JohnPerkin yes, i have entered my documentsservers domain name.
otherwise i would not see the mentioned error message. 

I also checked the network traffic with firebug.
the connection between the server and the page seems to be ok. 
During first tests, i got some problems with the websocket. But with the actual config, this problem seems to be gone. 

During the first tests, i got a 400 error when firefrox tried to reach the websocket. 
this is now working. Or at least, i dont get any errors.

**Comment by bigelectricccat** [comment]
It's a bit scattershot for me. I'm running Nextcloud 12.0.0 with integration app 1.0.5. In my case, Onlyoffice was installed onto a clean Ununtu Xenial base, with the node.js runner being proxied through Nginx. This is then proxied along with our Nextcloud through a second Nginx server. The example configs gave me enough to make the app and document server work with my proxy. 

However, I still see the "document cannot be saved" error message when attempting to open certain files. There's no good pattern for troubleshooting-- Docs created in Nextcloud generally don't throw the error. Editing an existing doc sometimes works normally, and sometimes doesn't. However, an affected file is always affected by the problem. Only thing of note in the debug logs is an auth reject that may or may not be caused by the app:

Warning	no app in context	Missing expected parameters in change user hook	2017-06-13T13:01:11-0500
Warning	no app in context	Missing expected parameters in change user hook	2017-06-13T13:01:11-0500
Debug	webdav	Sabre\DAV\Exception\NotAuthenticated: HTTP/1.1 401 No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured
[internal function] Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
/var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/owncloud/apps/dav/lib/Server.php - line 253: Sabre\DAV\Server->exec()
/var/www/owncloud/apps/dav/appinfo/v2/remote.php - line 33: OCA\DAV\Server->exec()
/var/www/owncloud/remote.php - line 162: require_once('/var/www/ownclo...')
{main}

For affected files, I can click through the error, then click "Hide menu" and begin editing. However, those files are not saved back to Nextcloud.

**Comment by io-node** [comment]
I have similar issues that OnlyOffice states it can't save the document. When checking the docker documentserver out.log file it states:

[2017-06-16 07:33:12.606] [ERROR] nodeJS - postData error: docId = 235979114968553931;url = http://cloud.domain.tld/apps/onlyoffice/track?doc=anR0aUZIdmYrOHF4WjZhTmhEbVlZZWY0Wkxub3ZZM2ZsRW5C
S0FkWkIxcz0/eyJmaWxlSWQiOjIzNTk3OTEsIm93bmVySWQiOiJhZG1pbiIsImFjdGlvbiI6InRyYWNrIn0%3D;data = {"key":"235979114968553931","status":1,"users":["admin"],"actions":[{"type":1,"userid":"admin"}]
}
Error: Error response: statusCode:404 ;body:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /apps/onlyoffice/track was not found on this server.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at cloud.domain.tld Port 80</address>
</body></html>

I have only set the Document Editing Service address to onlyoffice.domain.tld

**Comment by raphson93** [comment]
This problem happened in owncloud 10 with onlyoffice apps v1.1.1
Onlyoffice Document Server : 4.6.2
OS : Centos 7

Steps to reproduce:
1. Check the "csv" under the onlyoffice settings.

Logs:

> {"reqId":"WUjbEqc0tSE-K5G4BhFHLAAAAAU","level":1,"time":"June 20, 2017 16:21:39","remoteAddr":"175.143.72.221","user":"--","app":"onlyoffice","method":"POST","url":"\/index.php\/apps\/onlyoffice\/track?doc=aHhqc21Dd1l0UE1pTXZTdnJqNlhTa2RaSDVscCt0SDN0bHhzQm9EWWRTQT0\/eyJmaWxlSWQiOjM5NzkwODQsIm93bmVySWQiOiJhbGV4IiwiYWN0aW9uIjoidHJhY2sifQ%3D%3D","message":"Track with empty or not correct hash: hash not equal"}

**Comment by jhettler** [comment]
Hi all, similar issue after upgrading integration app from 1.0.4 to 1.1.3 on OwnCloud 9.1.6, DocumentServer 4.4.1.38, Onlyoffice integration app 1.1.3, OS Ubuntu 16.04 - I have set secret in default.json of DocumentServer, but if I set it in administration, I can't open and edit documents. If I leave the secret field in OC administration blank, everything works fine

/var/log/onlyoffice/documentserver/converter/out.log
```
[2017-07-09 01:13:32.106] [ERROR] nodeJS - error downloadFile:url=https://domain.com/owncloud/index.php/apps/onlyoffice/download?doc=NElSblV4S1hpTmp6eDcvSUlJNnZnL0hFZExXS09ocjBER3FPWVgxZ1ZCUT0/eyJmaWxlSWQiOjIzNjAyLCJvd25lcklkIjoiamFrdWIiLCJhY3Rpb24iOiJkb3dubG9hZCJ9;attempt=3;code:undefined;connect:undefined;(id=236021499548561)
Error: Error response: statusCode:403 ;body:
{"message":"Access denied"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:243:20)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
```

**Comment by alexanderonlyoffice** [comment]
@e-alfred, have you restarted the editors after setting up the secret in the editors' config? Please specify also if the document server and NextCloud are installed on one machine or on the different machines. 

Have you also sent us logs to support@onlyoffice.com?

**Comment by alexanderonlyoffice** [comment]
@bigelectricccat, please download the latest version of ONLYOFFICE integration app and check if the issue recurs.

**Comment by alexanderonlyoffice** [comment]
@io-node, please check the logs of the NextCloud, the reason of 403 error should be shown there.

**Comment by alexanderonlyoffice** [comment]
@jhettler, have you restarted the editors after setting up the secret in the editors' config? Please specify also if the document server and NextCloud are installed on one machine or on the different machines.

**Comment by alexanderonlyoffice** [comment]
@raphson93, please download the latest version of ONLYOFFICE integration app and check if the issue recurs.

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
