### ISSUE TITLE
Faulty Callback, no file accessed in Nextcloud log

### ISSUE THREAD

**Issue by pi-xel** [ONLYOFFICE/onlyoffice-owncloud#96]
Hi,

First off, thanks for the great work on OnlyOffice integration in Owncloud/Nextcloud.

I have compiled latest OnlyOffice GIT clone on an Arm (yes, that's possible, it's an ODroid XU4 running Debian Jessie) and am running Nextcloud 12.0.1 on it, with latest OnlyOffice integration 1.1.3. I am running OnlyOffice server on HTTPS and without a secret.

Everything is working well, I can create new files, edit existing ones and save them.

However, I have two issues:

1. The callback does not seem to work properly. Whenever I finish editing a document, after 10 seconds the following messages appear in my Nextcloud log:
```
Error	onlyoffice	GetConvertedUri in track: Error occurred in the document service: Unknown error
Error	PHP	Undefined index: extension at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#127
```
Apparently, the $document_uri variable is empty there.

Because the document extension cannot be extracted from the empty URI, also OnlyOffice File Converter logs an error such as:
```
[2017-08-13 11:08:21.310] [ERROR] nodeJS - stderr (id=9481851502610297_6540):
[2017-08-13 11:08:21.311] [ERROR] nodeJS - ExitCode (code=0;signal=SIGSEGV;error:-80;id=9481851502610297_6540)
```

2. For some reason (maybe related to 1.), edits are not saved in Nextcloud, i.e. when I create a document and edit it thereafter, the last modification shown in Nextcloud is still shown as the creation time.

Please help to resolve this isssues. If needed, I would be happy to provide more logs and trace variables.

Best regards,
pi-xel

**Comment by pi-xel** [comment]
Update: Apparently, edited documents are **NOT** correctly saved in NC. They are only somehow cashed within OnlyOffice, i.e. if I edit a document in OnlyOffice it says "saved" and when I exit the document and reopen it from NC, the document contains all modifications I made.

But when I download the document from NC and open it in e.g. Word, the modifications done with OnlyOffice are not there...

**Comment by pi-xel** [comment]
Update 2: Some more logs:
```
[2017-08-14 18:06:39.887] [INFO] nodeJS - Connection closed or timed out: userId = xxx1 isCloseConnection = true docId = 9738711502726770
[2017-08-14 18:06:44.912] [DEBUG] nodeJS - Start saveFromChanges: docId = 9738711502726770
[2017-08-14 18:06:45.017] [DEBUG] nodeJS - AddTask saveFromChanges: docId = 9738711502726770
[2017-08-14 18:06:45.671] [DEBUG] nodeJS - Start receiveTask: docId = 9738711502726770 {"cmd":{"c":"sfc","id":"9738711502726770","userid":"xxxx","data":null,"title":"output.","outputformat":2055,"outputpath":"output.","status_info":-80,"savekey":"9738711502726770_5374","useractionid":"xxxx"}}
[2017-08-14 18:06:45.721] [DEBUG] nodeJS - Start commandSfcCallback: docId = 9738711502726770
[2017-08-14 18:06:45.728] [DEBUG] nodeJS - Callback commandSfcCallback: docId = 9738711502726770 callback = https://127.0.0.1/index.php/apps/onlyoffice/track?doc=b0ZZWDVTRWk4QUw1d2VWOXpaQ3g5a2hTTmUzVm9QMWFPTWVFYXZCaDVyZz0/eyJmaWxlSWQiOjk3Mzg3MSwib3duZXJJZCI6InBoaWwiLCJhY3Rpb24iOiJ0cmFjayJ9
[2017-08-14 18:06:45.742] [DEBUG] nodeJS - hasEditors commandSfcCallback: docId = 9738711502726770 hasEditors = 0
[2017-08-14 18:06:45.766] [DEBUG] nodeJS - postData request: docId = 9738711502726770;url = https://127.0.0.1/index.php/apps/onlyoffice/track?doc=b0ZZWDVTRWk4QUw1d2VWOXpaQ3g5a2hTTmUzVm9QMWFPTWVFYXZCaDVyZz0/eyJmaWxlSWQiOjk3Mzg3MSwib3duZXJJZCI6InBoaWwiLCJhY3Rpb24iOiJ0cmFjayJ9;data = {"key":"9738711502726770","status":3,"users":["xxxx"],"actions":[{"type":0,"userid":"xxxx"}],"lastsave":"2017-08-14T16:06:33.930Z","notmodified":false}
[2017-08-14 18:06:46.032] [DEBUG] nodeJS - Start convert request docId = conv_973871_docx
[2017-08-14 18:06:46.091] [DEBUG] nodeJS - Start receiveTask: docId = conv_973871_docx {"cmd":{"c":"conv","id":"conv_973871_docx","format":"","url":null,"title":"output.docx","outputformat":65,"outputpath":"output.docx","codepage":46,"delimiter":4,"embeddedfonts":false,"status_info":-1}}
[2017-08-14 18:06:46.156] [DEBUG] nodeJS - End receiveTask: docId = conv_973871_docx
[2017-08-14 18:06:47.124] [DEBUG] nodeJS - End convert request url undefined status -1 docId = conv_973871_docx
[2017-08-14 18:06:47.174] [ERROR] nodeJS - sendServerRequest error: docId = 9738711502726770;url = https://127.0.0.1/index.php/apps/onlyoffice/track?doc=b0ZZWDVTRWk4QUw1d2VWOXpaQ3g5a2hTTmUzVm9QMWFPTWVFYXZCaDVyZz0/eyJmaWxlSWQiOjk3Mzg3MSwib3duZXJJZCI6InBoaWwiLCJhY3Rpb24iOiJ0cmFjayJ9;data = {"key":"9738711502726770","status":3,"users":["xxxx"],"actions":[{"type":0,"userid":"xxxx"}],"lastsave":"2017-08-14T16:06:33.930Z","notmodified":false}
Error: Error response: statusCode:500 ;body:
{"message":"Error occurred in the document service: Unknown error"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:269:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
[2017-08-14 18:06:47.188] [DEBUG] nodeJS - End commandSfcCallback: docId = 9738711502726770
[2017-08-14 18:06:47.191] [DEBUG] nodeJS - End receiveTask: docId = 9738711502726770
```

**Comment by ibnpetr** [comment]
Please try using "Download as" from the Editor's interface (after adding any changes to the document)
That is a way to figure out whether or not the issue is in the conversion process.

**Comment by pi-xel** [comment]
@ibnpetr Thanks for your response. The "download as" field is greyed out / not clickable in the editor.

**Comment by pi-xel** [comment]
@ibnpeter Sorry, did it on my phone and did not see the download buttons on the right :-) 

When I download from the editor, all changes are there. 
When I download from NC the changes do not appear.

**Comment by pi-xel** [comment]
Please also check my extended debug info in the other thread https://github.com/ONLYOFFICE/DocumentServer/issues/152.

**Comment by ibnpetr** [comment]
> Build finished, copied sdk-all.js and sdk-all-min.js to /var/www/onlyoffice/sdkjs/word - and it works flawlessly.

Please find and remove /var/www/onlyoffice/documentserver/sdkjs/word/sdk-all.cache

> Edit: From within editor everything works except "download as PDF".

btw, try opening any pdf file in the Editor, does it work?

**Comment by pi-xel** [comment]
@ibnpetr Removed sdk-all.cache, errors and log outputs remain the same.

And opening PDF files works flawlessly.
